defmodule WandererApp.Repo.Migrations.AddCharacterActivityRollup do
  @moduledoc """
  Adds the character activity rollup table and an age index on chain passages.

  This file was autogenerated with `mix ash_postgres.generate_migrations`, then trimmed:
  codegen also wanted to re-add `map_user_settings_v1.subscribed_system_ids`,
  `map_user_settings_v1.manually_added_system_ids` and `character_v1.needs_reauth`.
  Those columns already exist (see the hand-written migrations 20260816/20260817/20260821)
  — the resources had simply never been snapshotted, which this commit also fixes.
  """

  use Ecto.Migration

  def up do
    create index(:map_chain_passages_v1, [:inserted_at])

    create table(:character_activity_rollup_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :granularity, :text, null: false
      add :bucket_start, :date, null: false
      add :passages, :bigint, null: false, default: 0
      add :connections, :bigint, null: false, default: 0
      add :signatures, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :map_id,
          references(:maps_v1,
            column: :id,
            name: "character_activity_rollup_v1_map_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :character_id,
          references(:character_v1,
            column: :id,
            name: "character_activity_rollup_v1_character_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:character_activity_rollup_v1, [:granularity, :bucket_start])

    create unique_index(
             :character_activity_rollup_v1,
             [:map_id, :character_id, :granularity, :bucket_start],
             name: "character_activity_rollup_v1_unique_bucket_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :character_activity_rollup_v1,
                     [:map_id, :character_id, :granularity, :bucket_start],
                     name: "character_activity_rollup_v1_unique_bucket_index"
                   )

    drop constraint(:character_activity_rollup_v1, "character_activity_rollup_v1_map_id_fkey")

    drop constraint(
           :character_activity_rollup_v1,
           "character_activity_rollup_v1_character_id_fkey"
         )

    drop_if_exists index(:character_activity_rollup_v1, [:granularity, :bucket_start])

    drop table(:character_activity_rollup_v1)

    drop_if_exists index(:map_chain_passages_v1, [:inserted_at])
  end
end
